<?php

namespace Proxies\__CG__\Societies\TestEngineBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Nodes extends \Societies\TestEngineBundle\Entity\Nodes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNodeId($nodeId)
    {
        $this->__load();
        return parent::setNodeId($nodeId);
    }

    public function getNodeId()
    {
        $this->__load();
        return parent::getNodeId();
    }

    public function setNodeName($nodeName)
    {
        $this->__load();
        return parent::setNodeName($nodeName);
    }

    public function getNodeName()
    {
        $this->__load();
        return parent::getNodeName();
    }

    public function setNodeHost($nodeHost)
    {
        $this->__load();
        return parent::setNodeHost($nodeHost);
    }

    public function getNodeHost()
    {
        $this->__load();
        return parent::getNodeHost();
    }

    public function addPerformanceTestResult(\Societies\TestEngineBundle\Entity\PerformanceTestResult $performanceTestResults)
    {
        $this->__load();
        return parent::addPerformanceTestResult($performanceTestResults);
    }

    public function removePerformanceTestResult(\Societies\TestEngineBundle\Entity\PerformanceTestResult $performanceTestResults)
    {
        $this->__load();
        return parent::removePerformanceTestResult($performanceTestResults);
    }

    public function getPerformanceTestResults()
    {
        $this->__load();
        return parent::getPerformanceTestResults();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'node_id', 'node_name', 'node_host', 'performanceTestResults');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}