/**
 * Copyright (c) 2011, SOCIETIES Consortium (WATERFORD INSTITUTE OF TECHNOLOGY (TSSG), HERIOT-WATT UNIVERSITY (HWU), SOLUTA.NET 
 * (SN), GERMAN AEROSPACE CENTRE (Deutsches Zentrum fuer Luft- und Raumfahrt e.V.) (DLR), Zavod za varnostne tehnologije
 * informacijske družbe in elektronsko poslovanje (SETCCE), INSTITUTE OF COMMUNICATION AND COMPUTER SYSTEMS (ICCS), LAKE
 * COMMUNICATIONS (LAKE), INTEL PERFORMANCE LEARNING SOLUTIONS LTD (INTEL), PORTUGAL TELECOM INOVAÇÃO, SA (PTIN), IBM Corp., 
 * INSTITUT TELECOM (ITSUD), AMITEC DIACHYTI EFYIA PLIROFORIKI KAI EPIKINONIES ETERIA PERIORISMENIS EFTHINIS (AMITEC), TELECOM 
 * ITALIA S.p.a.(TI),  TRIALOG (TRIALOG), Stiftelsen SINTEF (SINTEF), NEC EUROPE LTD (NEC))
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
 * conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.societies.api.internal.devicemgmt.device;



/**
 * <font color="#3f5fbf">Handler for the events generated by the device</font>
 * @author rafik
 * @version 1.0
 * @created 06-d�c.-2011 15:38:57
 */
public interface DeviceListener {

	/**
	 * <font color="#3f5fbf">Device battery level has been updated.</font>
	 * <font color="#3f5fbf">It makes sense for devices implementing the Power Cluster.
	 * </font>
	 */
	public static final int EVENT_BATTERY_UPDATED = 4;
	/**
	 * <font color="#3f5fbf">Device has been disabled, so application must take care
	 * of it.</font>
	 */
	public static final int EVENT_DISABLED = 0;
	/**
	 * <font color="#3f5fbf">Device has been enabled and it is available</font>
	 */
	public static final int EVENT_ENABLED = 1;
	/**
	 * <font color="#3f5fbf">Device location has been updated.</font>
	 * <font color="#3f5fbf">It makes sense for devices implementing the Location
	 * Cluster.</font>
	 */
	public static final int EVENT_LOCATION_UPDATED = 3;
	/**
	 * <font color="#3f5fbf">Device is close be out of battery.</font>
	 * <font color="#3f5fbf">It makes sense for devices implementing the Power Cluster.
	 * </font>
	 */
	public static final int EVENT_LOW_BATTERY = 2;

	/**
	 * <font color="#3f5fbf">This method allows devices to notify other elements about
	 * events triggered by the device.</font>
	 * <font color="#7f9fbf"><b>@param</b></font><font color="#3f5fbf"> device Device
	 * that raised the event</font>
	 * <font color="#7f9fbf"><b>@param</b></font><font color="#3f5fbf"> event Event
	 * raised, one of the constanst defined in that interface</font>
	 * 
	 * @param device
	 * @param event
	 */
	public void deviceEvent(Device  device, int event);

}