package org.societies.api.internal.devicemgmt.device.actuator;

import org.societies.api.internal.devicemgmt.device.DeviceListener;



/**
 * <font color="#3f5fbf">Handler for the events generated by the actuator.</font>
 * @author rafik
 * @version 1.0
 * @created 06-déc.-2011 15:39:03
 */
public interface ActuatorListener extends DeviceListener {

	/**
	 * <font color="#3f5fbf">Status of the actuator has been changed as a result of a
	 * setStatus()</font>
	 * <font color="#3f5fbf">invocation.</font>
	 */
	public static final int EVENT_STATUS_CHANGED = 1;
	/**
	 * <font color="#3f5fbf">Status of the actuator has been retrieved an can be read
	 * (in actuators</font>
	 * <font color="#3f5fbf">implementing GetStatusActuatorCluster).</font>
	 */
	public static final int EVENT_STATUS_UPDATED = 0;

	/**
	 * 
	 * @param device
	 * @param event
	 */
	public void deviceActuatorEvent(Actuator device, int event);

}