/**
 * Copyright (c) 2011, SOCIETIES Consortium (WATERFORD INSTITUTE OF TECHNOLOGY (TSSG), HERIOT-WATT UNIVERSITY (HWU), SOLUTA.NET 
 * (SN), GERMAN AEROSPACE CENTRE (Deutsches Zentrum fuer Luft- und Raumfahrt e.V.) (DLR), Zavod za varnostne tehnologije
 * informacijske družbe in elektronsko poslovanje (SETCCE), INSTITUTE OF COMMUNICATION AND COMPUTER SYSTEMS (ICCS), LAKE
 * COMMUNICATIONS (LAKE), INTEL PERFORMANCE LEARNING SOLUTIONS LTD (INTEL), PORTUGAL TELECOM INOVAÇÃO, SA (PTIN), IBM Corp., 
 * INSTITUT TELECOM (ITSUD), AMITEC DIACHYTI EFYIA PLIROFORIKI KAI EPIKINONIES ETERIA PERIORISMENIS EFTHINIS (AMITEC), TELECOM 
 * ITALIA S.p.a.(TI),  TRIALOG (TRIALOG), Stiftelsen SINTEF (SINTEF), NEC EUROPE LTD (NEC))
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
 * conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.societies.context.similarity.reference;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
/**
 * Bureau of Labor Statistics				
 * On behalf of the Standard Occupational Classification Policy Committee (SOCPC)				
 *				
 *  January 2009				
 *  ** This is the final structure for the 2010 SOC.   Questions should be emailed to soc@bls.gov***				
 * 
 * @author John
 *
 */
public class OccupationRef {

	private HashMap<String,String> occupationList = new HashMap<String,String>();
	private String[] cat = new String[4];
	
	public OccupationRef(){
		popList();
		
	}
	
	public String[] find(String ocupation){
		String key = null;
		if ( occupationList.containsValue(ocupation)){
			
			for (Entry entry : occupationList.entrySet()) {
		        if (ocupation.equals(entry.getValue())) {
		            key = (String) entry.getKey();
		        }
		    }
		
			//  
			cat[0] = occupationList.get(key.substring(0, 2) + "-0000");
			cat[1] = occupationList.get(key.substring(0, 4) + "000");
			cat[2] = occupationList.get(key.substring(0, 6) + "0");
			if (!key.substring(6).equals("0")){
				cat[3] = ocupation;
			} 
		
		}
		//
		return cat;
	}
	


	
	private void popList(){
		occupationList.put("11-0000", "Management Occupation");
		occupationList.put("11-1000", "Top Executives");
		occupationList.put("11-1010", "Chief Executives");
		occupationList.put("11-1020", "General and Operations Managers");
		occupationList.put("11-1030", "Legislators");
		occupationList.put("11-2000", "Advertising, Marketing, Promotions, Public Relations, and Sales Managers");
		occupationList.put("11-2010", "Advertising and Promotions Managers");
		occupationList.put("11-2020", "Marketing and Sales Managers");
		occupationList.put("11-2021", "Marketing Managers");
		occupationList.put("11-2022", "Sales Managers");
		occupationList.put("11-2030", "Public Relations and Fundraising Managers");
		occupationList.put("11-3000", "Operations Specialties Managers");
		occupationList.put("11-3010", "Administrative Services Managers");
		occupationList.put("11-3020", "Computer and Information Systems Managers");
		occupationList.put("11-3030", "Financial Managers");
		occupationList.put("11-3050", "Industrial Production Managers");
		occupationList.put("11-3060", "Purchasing Managers");
		occupationList.put("11-3070", "Transportation, Storage, and Distribution Managers");
		occupationList.put("11-3110", "Compensation and Benefits Managers");
		occupationList.put("11-3120", "Human Resources Managers");
		occupationList.put("11-3130", "Training and Development Managers");
		occupationList.put("11-9000", "Other Management Occupations");
		occupationList.put("11-9010", "Farmers, Ranchers, and Other Agricultural Managers");
		occupationList.put("11-9020", "Construction Managers");
		occupationList.put("11-9030", "Education Administrators");
		occupationList.put("11-9031", "Education Administrators, Preschool and Childcare Center/Program");
		occupationList.put("11-9032", "Education Administrators, Elementary and Secondary School");
		occupationList.put("11-9033", "Education Administrators, Postsecondary");
		occupationList.put("11-9039", "Education Administrators, All Other");
		occupationList.put("11-9040", "Architectural and Engineering Managers");
		occupationList.put("11-9050", "Food Service Managers");
		occupationList.put("11-9060", "Funeral Service Managers");
		occupationList.put("11-9070", "Gaming Managers");
		occupationList.put("11-9080", "Lodging Managers");
		occupationList.put("11-9110", "Medical and Health Services Managers");
		occupationList.put("11-9120", "Natural Sciences Managers");
		occupationList.put("11-9130", "Postmasters and Mail Superintendents");
		occupationList.put("11-9140", "Property, Real Estate, and Community Association Managers");
		occupationList.put("11-9150", "Social and Community Service Managers");
		occupationList.put("11-9160", "Emergency Management Directors");
		occupationList.put("11-9190", "Miscellaneous Managers");
		occupationList.put("13-0000", "Business and Financial Operations Occupations");
		occupationList.put("13-1000", "Business Operations Specialists");
		occupationList.put("13-1010", "Agents and Business Managers of Artists, Performers, and Athletes");
		occupationList.put("13-1020", "Buyers and Purchasing Agents");
		occupationList.put("13-1021", "Buyers and Purchasing Agents, Farm Products");
		occupationList.put("13-1022", "Wholesale and Retail Buyers, Except Farm Products");
		occupationList.put("13-1023", "Purchasing Agents, Except Wholesale, Retail, and Farm Products");
		occupationList.put("13-1030", "Claims Adjusters, Appraisers, Examiners, and Investigators");
		occupationList.put("13-1040", "Compliance Officers");
		occupationList.put("13-1050", "Cost Estimators");
		occupationList.put("13-1070", "Human Resources Workers");
		occupationList.put("13-1080", "Logisticians");
		occupationList.put("13-1110", "Management Analysts");
		occupationList.put("13-1120", "Meeting, Convention, and Event Planners");
		occupationList.put("13-1130", "Fundraisers");
		occupationList.put("13-1140", "Compensation, Benefits, and Job Analysis Specialists");
		occupationList.put("13-1150", "Training and Development Specialists");
		occupationList.put("13-1160", "Market Research Analysts and Marketing Specialists");
		occupationList.put("13-1190", "Miscellaneous Business Operations Specialists");
		occupationList.put("13-2000", "Financial Specialists");
		occupationList.put("13-2010", "Accountants and Auditors");
		occupationList.put("13-2020", "Appraisers and Assessors of Real Estate");
		occupationList.put("13-2030", "Budget Analysts");
		occupationList.put("13-2040", "Credit Analysts");
		occupationList.put("13-2050", "Financial Analysts and Advisors");
		occupationList.put("13-2051", "Financial Analysts");
		occupationList.put("13-2052", "Personal Financial Advisors");
		occupationList.put("13-2053", "Insurance Underwriters");
		occupationList.put("13-2060", "Financial Examiners");
		occupationList.put("13-2070", "Credit Counselors and Loan Officers");
		occupationList.put("13-2071", "Credit Counselors");
		occupationList.put("13-2072", "Loan Officers");
		occupationList.put("13-2080", "Tax Examiners, Collectors and Preparers, and Revenue Agents");
		occupationList.put("13-2081", "Tax Examiners and Collectors, and Revenue Agents");
		occupationList.put("13-2082", "Tax Preparers");
		occupationList.put("13-2090", "Miscellaneous Financial Specialists");
		occupationList.put("15-0000", "Computer and Mathematical Occupations");
		occupationList.put("15-1100", "Computer Occupations");
		occupationList.put("15-1110", "Computer and Information Research Scientists");
		occupationList.put("15-1120", "Computer and Information Analysts");
		occupationList.put("15-1121", "Computer Systems Analysts");
		occupationList.put("15-1122", "Information Security Analysts");
		occupationList.put("15-1130", "Software Developers and Programmers");
		occupationList.put("15-1131", "Computer Programmers");
		occupationList.put("15-1132", "Software Developers, Applications");
		occupationList.put("15-1133", "Software Developers, Systems Software");
		occupationList.put("15-1134", "Web Developers");
		occupationList.put("15-1140", "Database and Systems Administrators and Network Architects");
		occupationList.put("15-1141", "Database Administrators");
		occupationList.put("15-1142", "Network and Computer Systems Administrators");
		occupationList.put("15-1143", "Computer Network Architects");
		occupationList.put("15-1150", "Computer Support Specialists");
		occupationList.put("15-1151", "Computer User Support Specialists");
		occupationList.put("15-1152", "Computer Network Support Specialists");
		occupationList.put("15-1190", "Miscellaneous Computer Occupations");
		occupationList.put("15-2000", "Mathematical Science Occupations");
		occupationList.put("15-2010", "Actuaries");
		occupationList.put("15-2020", "Mathematicians");
		occupationList.put("15-2030", "Operations Research Analysts");
		occupationList.put("15-2040", "Statisticians");
		occupationList.put("15-2090", "Miscellaneous Mathematical Science Occupations");
		occupationList.put("15-2091", "Mathematical Technicians");
		occupationList.put("15-2099", "Mathematical Science Occupations, All Other");
		occupationList.put("17-0000", "Architecture and Engineering Occupations");
		occupationList.put("17-1000", "Architects, Surveyors, and Cartographers");
		occupationList.put("17-1010", "Architects, Except Naval");
		occupationList.put("17-1011", "Architects, Except Landscape and Naval");
		occupationList.put("17-1012", "Landscape Architects");
		occupationList.put("17-1020", "Surveyors, Cartographers, and Photogrammetrists");
		occupationList.put("17-1021", "Cartographers and Photogrammetrists");
		occupationList.put("17-1022", "Surveyors");
		occupationList.put("17-2000", "Engineers");
		occupationList.put("17-2010", "Aerospace Engineers");
		occupationList.put("17-2020", "Agricultural Engineers");
		occupationList.put("17-2030", "Biomedical Engineers");
		occupationList.put("17-2040", "Chemical Engineers");
		occupationList.put("17-2050", "Civil Engineers");
		occupationList.put("17-2060", "Computer Hardware Engineers");
		occupationList.put("17-2070", "Electrical and Electronics Engineers");
		occupationList.put("17-2071", "Electrical Engineers");
		occupationList.put("17-2072", "Electronics Engineers, Except Computer");
		occupationList.put("17-2080", "Environmental Engineers");
		occupationList.put("17-2110", "Industrial Engineers, Including Health and Safety");
		occupationList.put("17-2111", "Health and Safety Engineers, Except Mining Safety Engineers and Inspectors");
		occupationList.put("17-2112", "Industrial Engineers");
		occupationList.put("17-2120", "Marine Engineers and Naval Architects");
		occupationList.put("17-2130", "Materials Engineers");
		occupationList.put("17-2140", "Mechanical Engineers");
		occupationList.put("17-2150", "Mining and Geological Engineers, Including Mining Safety Engineers");
		occupationList.put("17-2160", "Nuclear Engineers");
		occupationList.put("17-2170", "Petroleum Engineers");
		occupationList.put("17-2190", "Miscellaneous Engineers");
		occupationList.put("17-3000", "Drafters, Engineering Technicians, and Mapping Technicians");
		occupationList.put("17-3010", "Drafters");
		occupationList.put("17-3011", "Architectural and Civil Drafters");
		occupationList.put("17-3012", "Electrical and Electronics Drafters");
		occupationList.put("17-3013", "Mechanical Drafters");
		occupationList.put("17-3019", "Drafters, All Other");
		occupationList.put("17-3020", "Engineering Technicians, Except Drafters");
		occupationList.put("17-3021", "Aerospace Engineering and Operations Technicians");
		occupationList.put("17-3022", "Civil Engineering Technicians");
		occupationList.put("17-3023", "Electrical and Electronics Engineering Technicians");
		occupationList.put("17-3024", "Electro-Mechanical Technicians");
		occupationList.put("17-3025", "Environmental Engineering Technicians");
		occupationList.put("17-3026", "Industrial Engineering Technicians");
		occupationList.put("17-3027", "Mechanical Engineering Technicians");
		occupationList.put("17-3029", "Engineering Technicians, Except Drafters, All Other");
		occupationList.put("17-3030", "Surveying and Mapping Technicians");
		occupationList.put("19-0000", "Life, Physical, and Social Science Occupations");
		occupationList.put("19-1000", "Life Scientists");
		occupationList.put("19-1010", "Agricultural and Food Scientists");
		occupationList.put("19-1011", "Animal Scientists");
		occupationList.put("19-1012", "Food Scientists and Technologists");
		occupationList.put("19-1013", "Soil and Plant Scientists");
		occupationList.put("19-1020", "Biological Scientists");
		occupationList.put("19-1021", "Biochemists and Biophysicists");
		occupationList.put("19-1022", "Microbiologists");
		occupationList.put("19-1023", "Zoologists and Wildlife Biologists");
		occupationList.put("19-1029", "Biological Scientists, All Other");
		occupationList.put("19-1030", "Conservation Scientists and Foresters");
		occupationList.put("19-1031", "Conservation Scientists");
		occupationList.put("19-1032", "Foresters");
		occupationList.put("19-1040", "Medical Scientists");
		occupationList.put("19-1041", "Epidemiologists");
		occupationList.put("19-1042", "Medical Scientists, Except Epidemiologists");
		occupationList.put("19-1090", "Miscellaneous Life Scientists");
		occupationList.put("19-2000", "Physical Scientists");
		occupationList.put("19-2010", "Astronomers and Physicists");
		occupationList.put("19-2011", "Astronomers");
		occupationList.put("19-2012", "Physicists");
		occupationList.put("19-2020", "Atmospheric and Space Scientists");
		occupationList.put("19-2030", "Chemists and Materials Scientists");
		occupationList.put("19-2031", "Chemists");
		occupationList.put("19-2032", "Materials Scientists");
		occupationList.put("19-2040", "Environmental Scientists and Geoscientists");
		occupationList.put("19-2041", "Environmental Scientists and Specialists, Including Health");
		occupationList.put("19-2042", "Geoscientists, Except Hydrologists and Geographers");
		occupationList.put("19-2043", "Hydrologists");
		occupationList.put("19-2090", "Miscellaneous Physical Scientists");
		occupationList.put("19-3000", "Social Scientists and Related Workers");
		occupationList.put("19-3010", "Economists");
		occupationList.put("19-3020", "Survey Researchers");
		occupationList.put("19-3030", "Psychologists");
		occupationList.put("19-3031", "Clinical, Counseling, and School Psychologists");
		occupationList.put("19-3032", "Industrial-Organizational Psychologists");
		occupationList.put("19-3039", "Psychologists, All Other");
		occupationList.put("19-3040", "Sociologists");
		occupationList.put("19-3050", "Urban and Regional Planners");
		occupationList.put("19-3090", "Miscellaneous Social Scientists and Related Workers");
		occupationList.put("19-3091", "Anthropologists and Archeologists");
		occupationList.put("19-3092", "Geographers");
		occupationList.put("19-3093", "Historians");
		occupationList.put("19-3094", "Political Scientists");
		occupationList.put("19-3099", "Social Scientists and Related Workers, All Other");
		occupationList.put("19-4000", "Life, Physical, and Social Science Technicians");
		occupationList.put("19-4010", "Agricultural and Food Science Technicians");
		occupationList.put("19-4020", "Biological Technicians");
		occupationList.put("19-4030", "Chemical Technicians");
		occupationList.put("19-4040", "Geological and Petroleum Technicians");
		occupationList.put("19-4050", "Nuclear Technicians");
		occupationList.put("19-4060", "Social Science Research Assistants");
		occupationList.put("19-4090", "Miscellaneous Life, Physical, and Social Science Technicians");
		occupationList.put("19-4091", "Environmental Science and Protection Technicians, Including Health");
		occupationList.put("19-4092", "Forensic Science Technicians");
		occupationList.put("19-4093", "Forest and Conservation Technicians");
		occupationList.put("19-4099", "Life, Physical, and Social Science Technicians, All Other");
		occupationList.put("21-0000", "Community and Social Service Occupations");
		occupationList.put("21-1000", "Counselors, Social Workers, and Other Community and Social Service Specialists");
		occupationList.put("21-1010", "Counselors");
		occupationList.put("21-1011", "Substance Abuse and Behavioral Disorder Counselors");
		occupationList.put("21-1012", "Educational, Guidance, School, and Vocational Counselors");
		occupationList.put("21-1013", "Marriage and Family Therapists");
		occupationList.put("21-1014", "Mental Health Counselors");
		occupationList.put("21-1015", "Rehabilitation Counselors");
		occupationList.put("21-1019", "Counselors, All Other");
		occupationList.put("21-1020", "Social Workers");
		occupationList.put("21-1021", "Child, Family, and School Social Workers");
		occupationList.put("21-1022", "Healthcare Social Workers");
		occupationList.put("21-1023", "Mental Health and Substance Abuse Social Workers");
		occupationList.put("21-1029", "Social Workers, All Other");
		occupationList.put("21-1090", "Miscellaneous Community and Social Service Specialists");
		occupationList.put("21-1091", "Health Educators ");
		occupationList.put("21-1092", "Probation Officers and Correctional Treatment Specialists");
		occupationList.put("21-1093", "Social and Human Service Assistants");
		occupationList.put("21-1094", "Community Health Workers");
		occupationList.put("21-1099", "Community and Social Service Specialists, All Other");
		occupationList.put("21-2000", "Religious Workers");
		occupationList.put("21-2010", "Clergy");
		occupationList.put("21-2020", "Directors, Religious Activities and Education");
		occupationList.put("21-2090", "Miscellaneous Religious Workers");
		occupationList.put("23-0000", "Legal Occupations");
		occupationList.put("23-1000", "Lawyers, Judges, and Related Workers");
		occupationList.put("23-1010", "Lawyers and Judicial Law Clerks");
		occupationList.put("23-1011", "Lawyers");
		occupationList.put("23-1012", "Judicial Law Clerks");
		occupationList.put("23-1020", "Judges, Magistrates, and Other Judicial Workers");
		occupationList.put("23-1021", "Administrative Law Judges, Adjudicators, and Hearing Officers");
		occupationList.put("23-1022", "Arbitrators, Mediators, and Conciliators");
		occupationList.put("23-1023", "Judges, Magistrate Judges, and Magistrates");
		occupationList.put("23-2000", "Legal Support Workers");
		occupationList.put("23-2010", "Paralegals and Legal Assistants");
		occupationList.put("23-2090", "Miscellaneous Legal Support Workers");
		occupationList.put("23-2091", "Court Reporters");
		occupationList.put("23-2093", "Title Examiners, Abstractors, and Searchers");
		occupationList.put("23-2099", "Legal Support Workers, All Other");
		occupationList.put("25-0000", "Education, Training, and Library Occupations");
		occupationList.put("25-1000", "Postsecondary Teachers");
		occupationList.put("25-1010", "Business Teachers, Postsecondary");
		occupationList.put("25-1020", "Math and Computer Teachers, Postsecondary");
		occupationList.put("25-1021", "Computer Science Teachers, Postsecondary");
		occupationList.put("25-1022", "Mathematical Science Teachers, Postsecondary");
		occupationList.put("25-1030", "Engineering and Architecture Teachers, Postsecondary");
		occupationList.put("25-1031", "Architecture Teachers, Postsecondary");
		occupationList.put("25-1032", "Engineering Teachers, Postsecondary");
		occupationList.put("25-1040", "Life Sciences Teachers, Postsecondary");
		occupationList.put("25-1041", "Agricultural Sciences Teachers, Postsecondary");
		occupationList.put("25-1042", "Biological Science Teachers, Postsecondary");
		occupationList.put("25-1043", "Forestry and Conservation Science Teachers, Postsecondary");
		occupationList.put("25-1050", "Physical Sciences Teachers, Postsecondary");
		occupationList.put("25-1051", "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary");
		occupationList.put("25-1052", "Chemistry Teachers, Postsecondary");
		occupationList.put("25-1053", "Environmental Science Teachers, Postsecondary");
		occupationList.put("25-1054", "Physics Teachers, Postsecondary");
		occupationList.put("25-1060", "Social Sciences Teachers, Postsecondary");
		occupationList.put("25-1061", "Anthropology and Archeology Teachers, Postsecondary");
		occupationList.put("25-1062", "Area, Ethnic, and Cultural Studies Teachers, Postsecondary");
		occupationList.put("25-1063", "Economics Teachers, Postsecondary");
		occupationList.put("25-1064", "Geography Teachers, Postsecondary");
		occupationList.put("25-1065", "Political Science Teachers, Postsecondary");
		occupationList.put("25-1066", "Psychology Teachers, Postsecondary");
		occupationList.put("25-1067", "Sociology Teachers, Postsecondary");
		occupationList.put("25-1069", "Social Sciences Teachers, Postsecondary, All Other");
		occupationList.put("25-1070", "Health Teachers, Postsecondary");
		occupationList.put("25-1071", "Health Specialties Teachers, Postsecondary");
		occupationList.put("25-1072", "Nursing Instructors and Teachers, Postsecondary");
		occupationList.put("25-1080", "Education and Library Science Teachers, Postsecondary");
		occupationList.put("25-1081", "Education Teachers, Postsecondary");
		occupationList.put("25-1082", "Library Science Teachers, Postsecondary");
		occupationList.put("25-1110", "Law, Criminal Justice, and Social Work Teachers, Postsecondary");
		occupationList.put("25-1111", "Criminal Justice and Law Enforcement Teachers, Postsecondary");
		occupationList.put("25-1112", "Law Teachers, Postsecondary");
		occupationList.put("25-1113", "Social Work Teachers, Postsecondary");
		occupationList.put("25-1120", "Arts, Communications, and Humanities Teachers, Postsecondary");
		occupationList.put("25-1121", "Art, Drama, and Music Teachers, Postsecondary");
		occupationList.put("25-1122", "Communications Teachers, Postsecondary");
		occupationList.put("25-1123", "English Language and Literature Teachers, Postsecondary");
		occupationList.put("25-1124", "Foreign Language and Literature Teachers, Postsecondary");
		occupationList.put("25-1125", "History Teachers, Postsecondary");
		occupationList.put("25-1126", "Philosophy and Religion Teachers, Postsecondary");
		occupationList.put("25-1190", "Miscellaneous Postsecondary Teachers");
		occupationList.put("25-1191", "Graduate Teaching Assistants");
		occupationList.put("25-1192", "Home Economics Teachers, Postsecondary");
		occupationList.put("25-1193", "Recreation and Fitness Studies Teachers, Postsecondary");
		occupationList.put("25-1194", "Vocational Education Teachers, Postsecondary");
		occupationList.put("25-1199", "Postsecondary Teachers, All Other");
		occupationList.put("25-2000", "Preschool, Primary, Secondary, and Special Education School Teachers");
		occupationList.put("25-2010", "Preschool and Kindergarten Teachers");
		occupationList.put("25-2011", "Preschool Teachers, Except Special Education");
		occupationList.put("25-2012", "Kindergarten Teachers, Except Special Education");
		occupationList.put("25-2020", "Elementary and Middle School Teachers");
		occupationList.put("25-2021", "Elementary School Teachers, Except Special Education");
		occupationList.put("25-2022", "Middle School Teachers, Except Special and Career/Technical Education");
		occupationList.put("25-2023", "Career/Technical Education Teachers, Middle School");
		occupationList.put("25-2030", "Secondary School Teachers");
		occupationList.put("25-2031", "Secondary School Teachers, Except Special and Career/Technical Education");
		occupationList.put("25-2032", "Career/Technical Education Teachers, Secondary School");
		occupationList.put("25-2050", "Special Education Teachers");
		occupationList.put("25-2051", "Special Education Teachers, Preschool");
		occupationList.put("25-2052", "Special Education Teachers, Kindergarten and Elementary School");
		occupationList.put("25-2053", "Special Education Teachers, Middle School");
		occupationList.put("25-2054", "Special Education Teachers, Secondary School");
		occupationList.put("25-2059", "Special Education Teachers, All Other");
		occupationList.put("25-3000", "Other Teachers and Instructors");
		occupationList.put("25-3010", "Adult Basic and Secondary Education and Literacy Teachers and Instructors ");
		occupationList.put("25-3020", "Self-Enrichment Education Teachers");
		occupationList.put("25-3090", "Miscellaneous Teachers and Instructors");
		occupationList.put("25-4000", "Librarians, Curators, and Archivists");
		occupationList.put("25-4010", "Archivists, Curators, and Museum Technicians");
		occupationList.put("25-4011", "Archivists");
		occupationList.put("25-4012", "Curators");
		occupationList.put("25-4013", "Museum Technicians and Conservators");
		occupationList.put("25-4020", "Librarians");
		occupationList.put("25-4030", "Library Technicians");
		occupationList.put("25-9000", "Other Education, Training, and Library Occupations");
		occupationList.put("25-9010", "Audio-Visual and Multimedia Collections Specialists");
		occupationList.put("25-9020", "Farm and Home Management Advisors");
		occupationList.put("25-9030", "Instructional Coordinators");
		occupationList.put("25-9040", "Teacher Assistants");
		occupationList.put("25-9090", "Miscellaneous Education, Training, and Library Workers");
		occupationList.put("27-0000", "Arts, Design, Entertainment, Sports, and Media Occupations");
		occupationList.put("27-1000", "Art and Design Workers");
		occupationList.put("27-1010", "Artists and Related Workers");
		occupationList.put("27-1011", "Art Directors");
		occupationList.put("27-1012", "Craft Artists");
		occupationList.put("27-1013", "Fine Artists, Including Painters, Sculptors, and Illustrators");
		occupationList.put("27-1014", "Multimedia Artists and Animators");
		occupationList.put("27-1019", "Artists and Related Workers, All Other");
		occupationList.put("27-1020", "Designers");
		occupationList.put("27-1021", "Commercial and Industrial Designers");
		occupationList.put("27-1022", "Fashion Designers");
		occupationList.put("27-1023", "Floral Designers");
		occupationList.put("27-1024", "Graphic Designers");
		occupationList.put("27-1025", "Interior Designers");
		occupationList.put("27-1026", "Merchandise Displayers and Window Trimmers");
		occupationList.put("27-1027", "Set and Exhibit Designers");
		occupationList.put("27-1029", "Designers, All Other");
		occupationList.put("27-2000", "Entertainers and Performers, Sports and Related Workers");
		occupationList.put("27-2010", "Actors, Producers, and Directors");
		occupationList.put("27-2011", "Actors");
		occupationList.put("27-2012", "Producers and Directors");
		occupationList.put("27-2020", "Athletes, Coaches, Umpires, and Related Workers");
		occupationList.put("27-2021", "Athletes and Sports Competitors");
		occupationList.put("27-2022", "Coaches and Scouts");
		occupationList.put("27-2023", "Umpires, Referees, and Other Sports Officials");
		occupationList.put("27-2030", "Dancers and Choreographers");
		occupationList.put("27-2031", "Dancers");
		occupationList.put("27-2032", "Choreographers");
		occupationList.put("27-2040", "Musicians, Singers, and Related Workers");
		occupationList.put("27-2041", "Music Directors and Composers");
		occupationList.put("27-2042", "Musicians and Singers");
		occupationList.put("27-2090", "Miscellaneous Entertainers and Performers, Sports and Related Workers");
		occupationList.put("27-3000", "Media and Communication Workers");
		occupationList.put("27-3010", "Announcers");
		occupationList.put("27-3011", "Radio and Television Announcers");
		occupationList.put("27-3012", "Public Address System and Other Announcers");
		occupationList.put("27-3020", "News Analysts, Reporters and Correspondents");
		occupationList.put("27-3021", "Broadcast News Analysts");
		occupationList.put("27-3022", "Reporters and Correspondents");
		occupationList.put("27-3030", "Public Relations Specialists");
		occupationList.put("27-3040", "Writers and Editors");
		occupationList.put("27-3041", "Editors");
		occupationList.put("27-3042", "Technical Writers");
		occupationList.put("27-3043", "Writers and Authors");
		occupationList.put("27-3090", "Miscellaneous Media and Communication Workers");
		occupationList.put("27-3091", "Interpreters and Translators");
		occupationList.put("27-3099", "Media and Communication Workers, All Other");
		occupationList.put("27-4000", "Media and Communication Equipment Workers");
		occupationList.put("27-4010", "Broadcast and Sound Engineering Technicians and Radio Operators");
		occupationList.put("27-4011", "Audio and Video Equipment Technicians");
		occupationList.put("27-4012", "Broadcast Technicians");
		occupationList.put("27-4013", "Radio Operators");
		occupationList.put("27-4014", "Sound Engineering Technicians");
		occupationList.put("27-4020", "Photographers");
		occupationList.put("27-4030", "Television, Video, and Motion Picture Camera Operators and Editors");
		occupationList.put("27-4031", "Camera Operators, Television, Video, and Motion Picture");
		occupationList.put("27-4032", "Film and Video Editors");
		occupationList.put("27-4090", "Miscellaneous Media and Communication Equipment Workers");
		occupationList.put("29-0000", "Healthcare Practitioners and Technical Occupations");
		occupationList.put("29-1000", "Health Diagnosing and Treating Practitioners");
		occupationList.put("29-1010", "Chiropractors");
		occupationList.put("29-1020", "Dentists");
		occupationList.put("29-1021", "Dentists, General");
		occupationList.put("29-1022", "Oral and Maxillofacial Surgeons");
		occupationList.put("29-1023", "Orthodontists");
		occupationList.put("29-1024", "Prosthodontists");
		occupationList.put("29-1029", "Dentists, All Other Specialists");
		occupationList.put("29-1030", "Dietitians and Nutritionists");
		occupationList.put("29-1040", "Optometrists");
		occupationList.put("29-1050", "Pharmacists");
		occupationList.put("29-1060", "Physicians and Surgeons");
		occupationList.put("29-1061", "Anesthesiologists");
		occupationList.put("29-1062", "Family and General Practitioners");
		occupationList.put("29-1063", "Internists, General");
		occupationList.put("29-1064", "Obstetricians and Gynecologists");
		occupationList.put("29-1065", "Pediatricians, General");
		occupationList.put("29-1066", "Psychiatrists");
		occupationList.put("29-1067", "Surgeons");
		occupationList.put("29-1069", "Physicians and Surgeons, All Other");
		occupationList.put("29-1070", "Physician Assistants");
		occupationList.put("29-1080", "Podiatrists");
		occupationList.put("29-1120", "Therapists");
		occupationList.put("29-1122", "Occupational Therapists");
		occupationList.put("29-1123", "Physical Therapists");
		occupationList.put("29-1124", "Radiation Therapists");
		occupationList.put("29-1125", "Recreational Therapists");
		occupationList.put("29-1126", "Respiratory Therapists");
		occupationList.put("29-1127", "Speech-Language Pathologists");
		occupationList.put("29-1128", "Exercise Physiologists");
		occupationList.put("29-1129", "Therapists, All Other");
		occupationList.put("29-1130", "Veterinarians");
		occupationList.put("29-1140", "Registered Nurses");
		occupationList.put("29-1150", "Nurse Anesthetists");
		occupationList.put("29-1160", "Nurse Midwives");
		occupationList.put("29-1170", "Nurse Practitioners");
		occupationList.put("29-1180", "Audiologists");
		occupationList.put("29-1190", "Miscellaneous Health Diagnosing and Treating Practitioners");
		occupationList.put("29-2000", "Health Technologists and Technicians");
		occupationList.put("29-2010", "Clinical Laboratory Technologists and Technicians");
		occupationList.put("29-2011", "Medical and Clinical Laboratory Technologists");
		occupationList.put("29-2012", "Medical and Clinical Laboratory Technicians");
		occupationList.put("29-2020", "Dental Hygienists");
		occupationList.put("29-2030", "Diagnostic Related Technologists and Technicians");
		occupationList.put("29-2031", "Cardiovascular Technologists and Technicians");
		occupationList.put("29-2032", "Diagnostic Medical Sonographers");
		occupationList.put("29-2033", "Nuclear Medicine Technologists");
		occupationList.put("29-2034", "Radiologic Technologists ");
		occupationList.put("29-2035", "Magnetic Resonance Imaging Technologists");
		occupationList.put("29-2040", "Emergency Medical Technicians and Paramedics");
		occupationList.put("29-2050", "Health Practitioner Support Technologists and Technicians");
		occupationList.put("29-2051", "Dietetic Technicians");
		occupationList.put("29-2052", "Pharmacy Technicians");
		occupationList.put("29-2053", "Psychiatric Technicians");
		occupationList.put("29-2054", "Respiratory Therapy Technicians");
		occupationList.put("29-2055", "Surgical Technologists");
		occupationList.put("29-2056", "Veterinary Technologists and Technicians");
		occupationList.put("29-2057", "Ophthalmic Medical Technicians");
		occupationList.put("29-2060", "Licensed Practical and Licensed Vocational Nurses");
		occupationList.put("29-2070", "Medical Records and Health Information Technicians");
		occupationList.put("29-2080", "Opticians, Dispensing");
		occupationList.put("29-2090", "Miscellaneous Health Technologists and Technicians");
		occupationList.put("29-2091", "Orthotists and Prosthetists");
		occupationList.put("29-2092", "Hearing Aid Specialists");
		occupationList.put("29-2099", "Health Technologists and Technicians, All Other");
		occupationList.put("29-9000", "Other Healthcare Practitioners and Technical Occupations");
		occupationList.put("29-9010", "Occupational Health and Safety Specialists and Technicians");
		occupationList.put("29-9011", "Occupational Health and Safety Specialists");
		occupationList.put("29-9012", "Occupational Health and Safety Technicians");
		occupationList.put("29-9090", "Miscellaneous Health Practitioners and Technical Workers");
		occupationList.put("29-9091", "Athletic Trainers");
		occupationList.put("29-9092", "Genetic Counselors");
		occupationList.put("29-9099", "Healthcare Practitioners and Technical Workers, All Other");
		occupationList.put("31-0000", "Healthcare Support Occupations");
		occupationList.put("31-1000", "Nursing, Psychiatric, and Home Health Aides");
		occupationList.put("31-1010", "Nursing, Psychiatric, and Home Health Aides");
		occupationList.put("31-1011", "Home Health Aides");
		occupationList.put("31-1013", "Psychiatric Aides");
		occupationList.put("31-1014", "Nursing Assistants");
		occupationList.put("31-1015", "Orderlies");
		occupationList.put("31-2000", "Occupational Therapy and Physical Therapist Assistants and Aides");
		occupationList.put("31-2010", "Occupational Therapy Assistants and Aides");
		occupationList.put("31-2020", "Physical Therapist Assistants and Aides");
		occupationList.put("31-9000", "Other Healthcare Support Occupations");
		occupationList.put("31-9010", "Massage Therapists");
		occupationList.put("31-9090", "Miscellaneous Healthcare Support Occupations");
		occupationList.put("31-9091", "Dental Assistants");
		occupationList.put("31-9092", "Medical Assistants");
		occupationList.put("31-9093", "Medical Equipment Preparers");
		occupationList.put("31-9094", "Medical Transcriptionists");
		occupationList.put("31-9095", "Pharmacy Aides");
		occupationList.put("31-9096", "Veterinary Assistants and Laboratory Animal Caretakers");
		occupationList.put("31-9097", "Phlebotomists");
		occupationList.put("31-9099", "Healthcare Support Workers, All Other");
		occupationList.put("33-0000", "Protective Service Occupations");
		occupationList.put("33-1000", "Supervisors of Protective Service Workers");
		occupationList.put("33-1010", "First-Line Supervisors of Law Enforcement Workers");
		occupationList.put("33-1011", "First-Line Supervisors of Correctional Officers");
		occupationList.put("33-1012", "First-Line Supervisors of Police and Detectives");
		occupationList.put("33-1020", "First-Line Supervisors of Fire Fighting and Prevention Workers");
		occupationList.put("33-1090", "Miscellaneous First-Line Supervisors, Protective Service Workers");
		occupationList.put("33-2000", "Fire Fighting and Prevention Workers");
		occupationList.put("33-2010", "Firefighters");
		occupationList.put("31-2011", "Occupational Therapy Assistants");
		occupationList.put("31-2012", "Occupational Therapy Aides");
		occupationList.put("33-2020", "Fire Inspectors");
		occupationList.put("31-2021", "Physical Therapist Assistants");
		occupationList.put("31-2022", "Physical Therapist Aides");
		occupationList.put("33-3000", "Law Enforcement Workers");
		occupationList.put("33-3010", "Bailiffs, Correctional Officers, and Jailers");
		occupationList.put("33-3011", "Bailiffs");
		occupationList.put("33-3012", "Correctional Officers and Jailers");
		occupationList.put("33-3020", "Detectives and Criminal Investigators");
		occupationList.put("33-3030", "Fish and Game Wardens");
		occupationList.put("33-3040", "Parking Enforcement Workers");
		occupationList.put("33-3050", "Police Officers");
		occupationList.put("33-3051", "Police and Sheriff's Patrol Officers");
		occupationList.put("33-3052", "Transit and Railroad Police");
		occupationList.put("33-9000", "Other Protective Service Workers");
		occupationList.put("33-9010", "Animal Control Workers");
		occupationList.put("33-9020", "Private Detectives and Investigators");
		occupationList.put("33-9030", "Security Guards and Gaming Surveillance Officers");
		occupationList.put("33-9031", "Gaming Surveillance Officers and Gaming Investigators");
		occupationList.put("33-9032", "Security Guards");
		occupationList.put("33-9090", "Miscellaneous Protective Service Workers");
		occupationList.put("33-9091", "Crossing Guards");
		occupationList.put("33-9092", "Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers");
		occupationList.put("33-9093", "Transportation Security Screeners");
		occupationList.put("33-9099", "Protective Service Workers, All Other");
		occupationList.put("35-0000", "Food Preparation and Serving Related Occupations");
		occupationList.put("35-1000", "Supervisors of Food Preparation and Serving Workers");
		occupationList.put("35-1010", "Supervisors of Food Preparation and Serving Workers");
		occupationList.put("35-1011", "Chefs and Head Cooks");
		occupationList.put("35-1012", "First-Line Supervisors of Food Preparation and Serving Workers");
		occupationList.put("35-2000", "Cooks and Food Preparation Workers");
		occupationList.put("35-2010", "Cooks");
		occupationList.put("35-2011", "Cooks, Fast Food");
		occupationList.put("35-2012", "Cooks, Institution and Cafeteria");
		occupationList.put("35-2013", "Cooks, Private Household");
		occupationList.put("35-2014", "Cooks, Restaurant");
		occupationList.put("35-2015", "Cooks, Short Order");
		occupationList.put("35-2019", "Cooks, All Other");
		occupationList.put("35-2020", "Food Preparation Workers");
		occupationList.put("35-3000", "Food and Beverage Serving Workers");
		occupationList.put("35-3010", "Bartenders");
		occupationList.put("35-3020", "Fast Food and Counter Workers");
		occupationList.put("35-3021", "Combined Food Preparation and Serving Workers, Including Fast Food");
		occupationList.put("35-3022", "Counter Attendants, Cafeteria, Food Concession, and Coffee Shop");
		occupationList.put("35-3030", "Waiters and Waitresses");
		occupationList.put("35-3040", "Food Servers, Nonrestaurant");
		occupationList.put("35-9000", "Other Food Preparation and Serving Related Workers");
		occupationList.put("35-9010", "Dining Room and Cafeteria Attendants and Bartender Helpers");
		occupationList.put("35-9020", "Dishwashers");
		occupationList.put("35-9030", "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop");
		occupationList.put("35-9090", "Miscellaneous Food Preparation and Serving Related Workers");
		occupationList.put("37-0000", "Building and Grounds Cleaning and Maintenance Occupations");
		occupationList.put("37-1000", "Supervisors of Building and Grounds Cleaning and Maintenance Workers");
		occupationList.put("37-1010", "First-Line Supervisors of Building and Grounds Cleaning and Maintenance Workers");
		occupationList.put("39-1020", "First-Line Supervisors of Personal Service Workers");
		occupationList.put("37-2000", "Building Cleaning and Pest Control Workers");
		occupationList.put("37-2010", "Building Cleaning Workers");
		occupationList.put("37-2011", "Janitors and Cleaners, Except Maids and Housekeeping Cleaners");
		occupationList.put("37-2012", "Maids and Housekeeping Cleaners");
		occupationList.put("37-2019", "Building Cleaning Workers, All Other");
		occupationList.put("37-2020", "Pest Control Workers");
		occupationList.put("37-3000", "Grounds Maintenance Workers");
		occupationList.put("37-3010", "Grounds Maintenance Workers");
		occupationList.put("37-3011", "Landscaping and Groundskeeping Workers");
		occupationList.put("37-3012", "Pesticide Handlers, Sprayers, and Applicators, Vegetation");
		occupationList.put("37-3013", "Tree Trimmers and Pruners");
		occupationList.put("37-3019", "Grounds Maintenance Workers, All Other");
		occupationList.put("39-0000", "Personal Care and Service Occupations");
		occupationList.put("39-1000", "Supervisors of Personal Care and Service Workers");
		occupationList.put("39-1010", "First-Line Supervisors of Gaming Workers");
		occupationList.put("39-1011", "Gaming Supervisors");
		occupationList.put("39-1012", "Slot Supervisors");
		occupationList.put("39-1020", "First-Line Supervisors of Personal Service Workers");
		occupationList.put("39-2000", "Animal Care and Service Workers");
		occupationList.put("39-2010", "Animal Trainers");
		occupationList.put("39-2020", "Nonfarm Animal Caretakers");
		occupationList.put("39-3000", "Entertainment Attendants and Related Workers");
		occupationList.put("39-3010", "Gaming Services Workers");
		occupationList.put("39-3011", "Gaming Dealers");
		occupationList.put("39-3012", "Gaming and Sports Book Writers and Runners");
		occupationList.put("39-3019", "Gaming Service Workers, All Other");
		occupationList.put("39-3020", "Motion Picture Projectionists");
		occupationList.put("39-3030", "Ushers, Lobby Attendants, and Ticket Takers");
		occupationList.put("39-3090", "Miscellaneous Entertainment Attendants and Related Workers");
		occupationList.put("39-3091", "Amusement and Recreation Attendants");
		occupationList.put("39-3092", "Costume Attendants");
		occupationList.put("39-3093", "Locker Room, Coatroom, and Dressing Room Attendants");
		occupationList.put("39-3099", "Entertainment Attendants and Related Workers, All Other");
		occupationList.put("39-4000", "Funeral Service Workers");
		occupationList.put("39-4010", "Embalmers");
		occupationList.put("39-4020", "Funeral Attendants");
		occupationList.put("39-4030", "Morticians, Undertakers, and Funeral Directors");
		occupationList.put("39-5000", "Personal Appearance Workers");
		occupationList.put("39-5010", "Barbers, Hairdressers, Hairstylists and Cosmetologists");
		occupationList.put("39-5011", "Barbers");
		occupationList.put("39-5012", "Hairdressers, Hairstylists, and Cosmetologists");
		occupationList.put("39-5090", "Miscellaneous Personal Appearance Workers");
		occupationList.put("39-5091", "Makeup Artists, Theatrical and Performance");
		occupationList.put("39-5092", "Manicurists and Pedicurists");
		occupationList.put("39-5093", "Shampooers");
		occupationList.put("39-5094", "Skincare Specialists");
		occupationList.put("39-6000", "Baggage Porters, Bellhops, and Concierges");
		occupationList.put("39-6010", "Baggage Porters, Bellhops, and Concierges");
		occupationList.put("39-7000", "Tour and Travel Guides");
		occupationList.put("39-7010", "Tour and Travel Guides");
		occupationList.put("39-7011", "Tour Guides and Escorts");
		occupationList.put("39-7012", "Travel Guides");
		occupationList.put("39-9000", "Other Personal Care and Service Workers");
		occupationList.put("39-9010", "Childcare Workers");
		occupationList.put("39-9020", "Personal Care Aides");
		occupationList.put("39-9030", "Recreation and Fitness Workers");
		occupationList.put("39-9031", "Fitness Trainers and Aerobics Instructors");
		occupationList.put("39-9032", "Recreation Workers");
		occupationList.put("39-9040", "Residential Advisors");
		occupationList.put("39-9090", "Miscellaneous Personal Care and Service Workers");
		occupationList.put("41-0000", "Sales and Related Occupations");
		occupationList.put("41-1000", "Supervisors of Sales Workers");
		occupationList.put("41-1010", "First-Line Supervisors of Sales Workers");
		occupationList.put("41-1011", "First-Line Supervisors of Retail Sales Workers");
		occupationList.put("41-1012", "First-Line Supervisors of Non-Retail Sales Workers");
		occupationList.put("41-2000", "Retail Sales Workers");
		occupationList.put("41-2010", "Cashiers");
		occupationList.put("41-2011", "Cashiers");
		occupationList.put("41-2012", "Gaming Change Persons and Booth Cashiers");
		occupationList.put("41-2020", "Counter and Rental Clerks and Parts Salespersons");
		occupationList.put("41-2021", "Counter and Rental Clerks");
		occupationList.put("41-2022", "Parts Salespersons");
		occupationList.put("41-2030", "Retail Salespersons");
		occupationList.put("41-3000", "Sales Representatives, Services");
		occupationList.put("41-3010", "Advertising Sales Agents");
		occupationList.put("41-3020", "Insurance Sales Agents");
		occupationList.put("41-3030", "Securities, Commodities, and Financial Services Sales Agents");
		occupationList.put("41-3040", "Travel Agents");
		occupationList.put("41-3090", "Miscellaneous Sales Representatives, Services");
		occupationList.put("41-4000", "Sales Representatives, Wholesale and Manufacturing");
		occupationList.put("41-4010", "Sales Representatives, Wholesale and Manufacturing");
		occupationList.put("41-9000", "Other Sales and Related Workers");
		occupationList.put("41-9010", "Models, Demonstrators, and Product Promoters");
		occupationList.put("41-9011", "Demonstrators and Product Promoters");
		occupationList.put("41-9012", "Models");
		occupationList.put("41-9020", "Real Estate Brokers and Sales Agents");
		occupationList.put("41-9021", "Real Estate Brokers");
		occupationList.put("41-9022", "Real Estate Sales Agents");
		occupationList.put("41-9030", "Sales Engineers");
		occupationList.put("41-9040", "Telemarketers");
		occupationList.put("41-9090", "Miscellaneous Sales and Related Workers");
		occupationList.put("41-9091", "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers");
		occupationList.put("41-9099", "Sales and Related Workers, All Other");
		occupationList.put("43-0000", "Office and Administrative Support Occupations");
		occupationList.put("43-1000", "Supervisors of Office and Administrative Support Workers");
		occupationList.put("43-1010", "First-Line Supervisors of Office and Administrative Support Workers");
		occupationList.put("43-2000", "Communications Equipment Operators");
		occupationList.put("43-2010", "Switchboard Operators, Including Answering Service");
		occupationList.put("43-2020", "Telephone Operators");
		occupationList.put("43-2090", "Miscellaneous Communications Equipment Operators");
		occupationList.put("43-3000", "Financial Clerks");
		occupationList.put("43-3010", "Bill and Account Collectors");
		occupationList.put("43-3020", "Billing and Posting Clerks");
		occupationList.put("43-3030", "Bookkeeping, Accounting, and Auditing Clerks");
		occupationList.put("43-3040", "Gaming Cage Workers");
		occupationList.put("43-3050", "Payroll and Timekeeping Clerks");
		occupationList.put("43-3060", "Procurement Clerks");
		occupationList.put("43-3070", "Tellers");
		occupationList.put("43-3090", "Miscellaneous Financial Clerks");
		occupationList.put("43-4000", "Information and Record Clerks");
		occupationList.put("43-4010", "Brokerage Clerks");
		occupationList.put("43-4020", "Correspondence Clerks");
		occupationList.put("43-4030", "Court, Municipal, and License Clerks");
		occupationList.put("43-4040", "Credit Authorizers, Checkers, and Clerks");
		occupationList.put("43-4050", "Customer Service Representatives");
		occupationList.put("43-4060", "Eligibility Interviewers, Government Programs");
		occupationList.put("43-4070", "File Clerks");
		occupationList.put("43-4080", "Hotel, Motel, and Resort Desk Clerks");
		occupationList.put("43-4110", "Interviewers, Except Eligibility and Loan");
		occupationList.put("43-4120", "Library Assistants, Clerical");
		occupationList.put("43-4130", "Loan Interviewers and Clerks");
		occupationList.put("43-4140", "New Accounts Clerks");
		occupationList.put("43-4150", "Order Clerks");
		occupationList.put("43-4160", "Human Resources Assistants, Except Payroll and Timekeeping");
		occupationList.put("43-4170", "Receptionists and Information Clerks");
		occupationList.put("43-4180", "Reservation and Transportation Ticket Agents and Travel Clerks");
		occupationList.put("43-4190", "Miscellaneous Information and Record Clerks");
		occupationList.put("43-5000", "Material Recording, Scheduling, Dispatching, and Distributing Workers");
		occupationList.put("43-5010", "Cargo and Freight Agents");
		occupationList.put("43-5020", "Couriers and Messengers");
		occupationList.put("43-5030", "Dispatchers");
		occupationList.put("43-5040", "Meter Readers, Utilities");
		occupationList.put("43-5050", "Postal Service Workers");
		occupationList.put("43-5051", "Postal Service Clerks");
		occupationList.put("43-5052", "Postal Service Mail Carriers");
		occupationList.put("43-5053", "Postal Service Mail Sorters, Processors, and Processing Machine Operators");
		occupationList.put("43-5060", "Production, Planning, and Expediting Clerks");
		occupationList.put("43-5070", "Shipping, Receiving, and Traffic Clerks");
		occupationList.put("43-5080", "Stock Clerks and Order Fillers");
		occupationList.put("43-5110", "Weighers, Measurers, Checkers, and Samplers, Recordkeeping");
		occupationList.put("43-6000", "Secretaries and Administrative Assistants");
		occupationList.put("43-6010", "Secretaries and Administrative Assistants");
		occupationList.put("43-9000", "Other Office and Administrative Support Workers");
		occupationList.put("43-9010", "Computer Operators");
		occupationList.put("43-9020", "Data Entry and Information Processing Workers");
		occupationList.put("43-9030", "Desktop Publishers");
		occupationList.put("43-9040", "Insurance Claims and Policy Processing Clerks");
		occupationList.put("43-9050", "Mail Clerks and Mail Machine Operators, Except Postal Service");
		occupationList.put("43-9060", "Office Clerks, General");
		occupationList.put("43-9070", "Office Machine Operators, Except Computer");
		occupationList.put("43-9080", "Proofreaders and Copy Markers");
		occupationList.put("43-9110", "Statistical Assistants");
		occupationList.put("43-9190", "Miscellaneous Office and Administrative Support Workers");
		occupationList.put("45-0000", "Farming, Fishing, and Forestry Occupations");
		occupationList.put("45-1000", "Supervisors of Farming, Fishing, and Forestry Workers");
		occupationList.put("45-1010", "First-Line Supervisors of Farming, Fishing, and Forestry Workers");
		occupationList.put("45-2000", "Agricultural Workers");
		occupationList.put("45-2010", "Agricultural Inspectors");
		occupationList.put("45-2020", "Animal Breeders");
		occupationList.put("45-2040", "Graders and Sorters, Agricultural Products");
		occupationList.put("45-2090", "Miscellaneous Agricultural Workers");
		occupationList.put("45-2091", "Agricultural Equipment Operators");
		occupationList.put("45-2092", "Farmworkers and Laborers, Crop, Nursery, and Greenhouse");
		occupationList.put("45-2093", "Farmworkers, Farm, Ranch, and Aquacultural Animals");
		occupationList.put("45-2099", "Agricultural Workers, All Other");
		occupationList.put("45-3000", "Fishing and Hunting Workers");
		occupationList.put("45-3010", "Fishers and Related Fishing Workers");
		occupationList.put("45-3020", "Hunters and Trappers");
		occupationList.put("45-4000", "Forest, Conservation, and Logging Workers");
		occupationList.put("45-4010", "Forest and Conservation Workers");
		occupationList.put("45-4020", "Logging Workers");
		occupationList.put("45-4021", "Fallers");
		occupationList.put("45-4022", "Logging Equipment Operators");
		occupationList.put("45-4023", "Log Graders and Scalers");
		occupationList.put("45-4029", "Logging Workers, All Other");
		occupationList.put("47-0000", "Construction and Extraction Occupations");
		occupationList.put("47-1000", "Supervisors of Construction and Extraction Workers");
		occupationList.put("47-1010", "First-Line Supervisors of Construction Trades and Extraction Workers");
		occupationList.put("47-2000", "Construction Trades Workers");
		occupationList.put("47-2010", "Boilermakers");
		occupationList.put("47-2020", "Brickmasons, Blockmasons, and Stonemasons");
		occupationList.put("47-2021", "Brickmasons and Blockmasons");
		occupationList.put("47-2022", "Stonemasons");
		occupationList.put("47-2030", "Carpenters");
		occupationList.put("47-2040", "Carpet, Floor, and Tile Installers and Finishers");
		occupationList.put("47-2050", "Cement Masons, Concrete Finishers, and Terrazzo Workers");
		occupationList.put("47-2060", "Construction Laborers");
		occupationList.put("47-2070", "Construction Equipment Operators");
		occupationList.put("47-2080", "Drywall Installers, Ceiling Tile Installers, and Tapers");
		occupationList.put("47-2110", "Electricians");
		occupationList.put("47-2120", "Glaziers");
		occupationList.put("47-2130", "Insulation Workers");
		occupationList.put("47-2140", "Painters and Paperhangers");
		occupationList.put("47-2041", "Carpet Installers");
		occupationList.put("47-2042", "Floor Layers, Except Carpet, Wood, and Hard Tiles");
		occupationList.put("47-2043", "Floor Sanders and Finishers");
		occupationList.put("47-2044", "Tile and Marble Setters");
		occupationList.put("47-2150", "Pipelayers, Plumbers, Pipefitters, and Steamfitters");
		occupationList.put("47-2051", "Cement Masons and Concrete Finishers");
		occupationList.put("47-2053", "Terrazzo Workers and Finishers");
		occupationList.put("47-2160", "Plasterers and Stucco Masons");
		occupationList.put("47-2170", "Reinforcing Iron and Rebar Workers");
		occupationList.put("47-2071", "Paving, Surfacing, and Tamping Equipment Operators");
		occupationList.put("47-2072", "Pile-Driver Operators");
		occupationList.put("47-2073", "Operating Engineers and Other Construction Equipment Operators");
		occupationList.put("47-2180", "Roofers");
		occupationList.put("47-2081", "Drywall and Ceiling Tile Installers");
		occupationList.put("47-2082", "Tapers");
		occupationList.put("47-2210", "Sheet Metal Workers");
		occupationList.put("47-2220", "Structural Iron and Steel Workers");
		occupationList.put("47-2230", "Solar Photovoltaic Installers");
		occupationList.put("47-2131", "Insulation Workers, Floor, Ceiling, and Wall");
		occupationList.put("47-2132", "Insulation Workers, Mechanical");
		occupationList.put("47-2140", "Painters and Paperhangers");
		occupationList.put("47-2141", "Painters, Construction and Maintenance");
		occupationList.put("47-2142", "Paperhangers");
		occupationList.put("47-2150", "Pipelayers, Plumbers, Pipefitters, and Steamfitters");
		occupationList.put("47-2151", "Pipelayers");
		occupationList.put("47-2152", "Plumbers, Pipefitters, and Steamfitters");
		occupationList.put("47-2160", "Plasterers and Stucco Masons");
		occupationList.put("47-2170", "Reinforcing Iron and Rebar Workers");
		occupationList.put("47-2180", "Roofers");
		occupationList.put("47-2210", "Sheet Metal Workers");
		occupationList.put("47-2220", "Structural Iron and Steel Workers");
		occupationList.put("47-2230", "Solar Photovoltaic Installers");
		occupationList.put("47-3000", "Helpers, Construction Trades");
		occupationList.put("47-3010", "Helpers, Construction Trades");
		occupationList.put("47-3011", "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters");
		occupationList.put("47-3012", "Helpers--Carpenters");
		occupationList.put("47-3013", "Helpers--Electricians");
		occupationList.put("47-3014", "Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons");
		occupationList.put("47-3015", "Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters");
		occupationList.put("47-3016", "Helpers--Roofers");
		occupationList.put("47-3019", "Helpers, Construction Trades, All Other");
		occupationList.put("47-4000", "Other Construction and Related Workers");
		occupationList.put("47-4010", "Construction and Building Inspectors");
		occupationList.put("47-4020", "Elevator Installers and Repairers");
		occupationList.put("47-4030", "Fence Erectors");
		occupationList.put("47-4040", "Hazardous Materials Removal Workers");
		occupationList.put("47-4050", "Highway Maintenance Workers");
		occupationList.put("47-4060", "Rail-Track Laying and Maintenance Equipment Operators");
		occupationList.put("47-4070", "Septic Tank Servicers and Sewer Pipe Cleaners");
		occupationList.put("47-4090", "Miscellaneous Construction and Related Workers");
		occupationList.put("47-4091", "Segmental Pavers");
		occupationList.put("47-4099", "Construction and Related Workers, All Other");
		occupationList.put("47-5000", "Extraction Workers");
		occupationList.put("47-5010", "Derrick, Rotary Drill, and Service Unit Operators, Oil, Gas, and Mining");
		occupationList.put("47-5011", "Derrick Operators, Oil and Gas");
		occupationList.put("47-5012", "Rotary Drill Operators, Oil and Gas");
		occupationList.put("47-5013", "Service Unit Operators, Oil, Gas, and Mining");
		occupationList.put("47-5020", "Earth Drillers, Except Oil and Gas");
		occupationList.put("47-5030", "Explosives Workers, Ordnance Handling Experts, and Blasters");
		occupationList.put("47-5040", "Mining Machine Operators");
		occupationList.put("47-5041", "Continuous Mining Machine Operators");
		occupationList.put("47-5042", "Mine Cutting and Channeling Machine Operators");
		occupationList.put("47-5049", "Mining Machine Operators, All Other");
		occupationList.put("47-5060", "Roof Bolters, Mining");
		occupationList.put("47-5070", "Roustabouts, Oil and Gas");
		occupationList.put("47-5080", "Helpers--Extraction Workers");
		occupationList.put("47-5090", "Miscellaneous Extraction Workers");
		occupationList.put("49-0000", "Installation, Maintenance, and Repair Occupations");
		occupationList.put("49-1000", "Supervisors of Installation, Maintenance, and Repair Workers");
		occupationList.put("49-1010", "First-Line Supervisors of Mechanics, Installers, and Repairers");
		occupationList.put("49-2000", "Electrical and Electronic Equipment Mechanics, Installers, and Repairers");
		occupationList.put("49-2010", "Computer, Automated Teller, and Office Machine Repairers");
		occupationList.put("49-2020", "Radio and Telecommunications Equipment Installers and Repairers");
		occupationList.put("49-2090", "Miscellaneous Electrical and Electronic Equipment Mechanics, Installers, and Repairers");
		occupationList.put("49-2091", "Avionics Technicians");
		occupationList.put("49-2092", "Electric Motor, Power Tool, and Related Repairers");
		occupationList.put("49-2093", "Electrical and Electronics Installers and Repairers, Transportation Equipment");
		occupationList.put("49-2094", "Electrical and Electronics Repairers, Commercial and Industrial Equipment");
		occupationList.put("49-2095", "Electrical and Electronics Repairers, Powerhouse, Substation, and Relay");
		occupationList.put("49-2096", "Electronic Equipment Installers and Repairers, Motor Vehicles");
		occupationList.put("49-2097", "Electronic Home Entertainment Equipment Installers and Repairers");
		occupationList.put("49-2098", "Security and Fire Alarm Systems Installers");
		occupationList.put("49-3000", "Vehicle and Mobile Equipment Mechanics, Installers, and Repairers");
		occupationList.put("49-3010", "Aircraft Mechanics and Service Technicians");
		occupationList.put("49-3020", "Automotive Technicians and Repairers");
		occupationList.put("49-3021", "Automotive Body and Related Repairers");
		occupationList.put("49-3022", "Automotive Glass Installers and Repairers");
		occupationList.put("49-3023", "Automotive Service Technicians and Mechanics");
		occupationList.put("49-3030", "Bus and Truck Mechanics and Diesel Engine Specialists");
		occupationList.put("49-3040", "Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics");
		occupationList.put("49-3041", "Farm Equipment Mechanics and Service Technicians");
		occupationList.put("49-3042", "Mobile Heavy Equipment Mechanics, Except Engines");
		occupationList.put("49-3043", "Rail Car Repairers");
		occupationList.put("49-3050", "Small Engine Mechanics");
		occupationList.put("49-3051", "Motorboat Mechanics and Service Technicians");
		occupationList.put("49-3052", "Motorcycle Mechanics");
		occupationList.put("49-3053", "Outdoor Power Equipment and Other Small Engine Mechanics");
		occupationList.put("49-3090", "Miscellaneous Vehicle and Mobile Equipment Mechanics, Installers, and Repairers");
		occupationList.put("49-3091", "Bicycle Repairers");
		occupationList.put("49-3092", "Recreational Vehicle Service Technicians");
		occupationList.put("49-3093", "Tire Repairers and Changers");
		occupationList.put("49-9000", "Other Installation, Maintenance, and Repair Occupations");
		occupationList.put("49-9010", "Control and Valve Installers and Repairers");
		occupationList.put("49-9011", "Mechanical Door Repairers");
		occupationList.put("49-9012", "Control and Valve Installers and Repairers, Except Mechanical Door");
		occupationList.put("49-9020", "Heating, Air Conditioning, and Refrigeration Mechanics and Installers");
		occupationList.put("49-9030", "Home Appliance Repairers");
		occupationList.put("49-9040", "Industrial Machinery Installation, Repair, and Maintenance Workers");
		occupationList.put("49-9041", "Industrial Machinery Mechanics");
		occupationList.put("49-9043", "Maintenance Workers, Machinery");
		occupationList.put("49-9044", "Millwrights");
		occupationList.put("49-9045", "Refractory Materials Repairers, Except Brickmasons");
		occupationList.put("49-9050", "Line Installers and Repairers");
		occupationList.put("49-9051", "Electrical Power-Line Installers and Repairers");
		occupationList.put("49-9052", "Telecommunications Line Installers and Repairers");
		occupationList.put("49-9060", "Precision Instrument and Equipment Repairers");
		occupationList.put("49-9061", "Camera and Photographic Equipment Repairers");
		occupationList.put("49-9062", "Medical Equipment Repairers");
		occupationList.put("49-9063", "Musical Instrument Repairers and Tuners");
		occupationList.put("49-9064", "Watch Repairers");
		occupationList.put("49-9069", "Precision Instrument and Equipment Repairers, All Other");
		occupationList.put("49-9070", "Maintenance and Repair Workers, General");
		occupationList.put("49-9080", "Wind Turbine Service Technicians");
		occupationList.put("49-9090", "Miscellaneous Installation, Maintenance, and Repair Workers");
		occupationList.put("49-9091", "Coin, Vending, and Amusement Machine Servicers and Repairers");
		occupationList.put("49-9092", "Commercial Divers");
		occupationList.put("49-9093", "Fabric Menders, Except Garment");
		occupationList.put("49-9094", "Locksmiths and Safe Repairers");
		occupationList.put("49-9095", "Manufactured Building and Mobile Home Installers");
		occupationList.put("49-9096", "Riggers");
		occupationList.put("49-9097", "Signal and Track Switch Repairers");
		occupationList.put("49-9098", "Helpers--Installation, Maintenance, and Repair Workers");
		occupationList.put("49-9099", "Installation, Maintenance, and Repair Workers, All Other");
		occupationList.put("51-0000", "Production Occupations");
		occupationList.put("51-1000", "Supervisors of Production Workers");
		occupationList.put("51-1010", "First-Line Supervisors of Production and Operating Workers");
		occupationList.put("51-2000", "Assemblers and Fabricators");
		occupationList.put("51-2010", "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers");
		occupationList.put("51-2020", "Electrical, Electronics, and Electromechanical Assemblers");
		occupationList.put("51-2021", "Coil Winders, Tapers, and Finishers");
		occupationList.put("51-2022", "Electrical and Electronic Equipment Assemblers");
		occupationList.put("51-2023", "Electromechanical Equipment Assemblers");
		occupationList.put("51-2030", "Engine and Other Machine Assemblers");
		occupationList.put("51-2040", "Structural Metal Fabricators and Fitters");
		occupationList.put("51-2090", "Miscellaneous Assemblers and Fabricators");
		occupationList.put("51-2091", "Fiberglass Laminators and Fabricators");
		occupationList.put("51-2092", "Team Assemblers");
		occupationList.put("51-2093", "Timing Device Assemblers and Adjusters");
		occupationList.put("51-2099", "Assemblers and Fabricators, All Other");
		occupationList.put("51-3000", "Food Processing Workers");
		occupationList.put("51-3010", "Bakers");
		occupationList.put("51-3020", "Butchers and Other Meat, Poultry, and Fish Processing Workers");
		occupationList.put("51-3021", "Butchers and Meat Cutters");
		occupationList.put("51-3022", "Meat, Poultry, and Fish Cutters and Trimmers");
		occupationList.put("51-3023", "Slaughterers and Meat Packers");
		occupationList.put("51-3090", "Miscellaneous Food Processing Workers");
		occupationList.put("51-3091", "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders");
		occupationList.put("51-3092", "Food Batchmakers");
		occupationList.put("51-3093", "Food Cooking Machine Operators and Tenders");
		occupationList.put("51-3099", "Food Processing Workers, All Other");
		occupationList.put("51-4000", "Metal Workers and Plastic Workers");
		occupationList.put("51-4010", "Computer Control Programmers and Operators");
		occupationList.put("51-4020", "Forming Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4021", "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4022", "Forging Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4023", "Rolling Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4030", "Machine Tool Cutting Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4031", "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4032", "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4033", "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4034", "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4035", "Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4040", "Machinists");
		occupationList.put("51-4050", "Metal Furnace Operators, Tenders, Pourers, and Casters");
		occupationList.put("51-4060", "Model Makers and Patternmakers, Metal and Plastic");
		occupationList.put("51-4070", "Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4080", "Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4110", "Tool and Die Makers");
		occupationList.put("51-4120", "Welding, Soldering, and Brazing Workers");
		occupationList.put("51-4121", "Welders, Cutters, Solderers, and Brazers");
		occupationList.put("51-4122", "Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders");
		occupationList.put("51-4190", "Miscellaneous Metal Workers and Plastic Workers");
		occupationList.put("51-4191", "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4192", "Layout Workers, Metal and Plastic");
		occupationList.put("51-4193", "Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic");
		occupationList.put("51-4194", "Tool Grinders, Filers, and Sharpeners");
		occupationList.put("51-4199", "Metal Workers and Plastic Workers, All Other");
		occupationList.put("51-5100", "Printing Workers");
		occupationList.put("51-5110", "Printing Workers");
		occupationList.put("51-5111", "Prepress Technicians and Workers");
		occupationList.put("51-5112", "Printing Press Operators");
		occupationList.put("51-5113", "Print Binding and Finishing Workers");
		occupationList.put("51-6000", "Textile, Apparel, and Furnishings Workers");
		occupationList.put("51-6010", "Laundry and Dry-Cleaning Workers");
		occupationList.put("51-6020", "Pressers, Textile, Garment, and Related Materials");
		occupationList.put("51-6030", "Sewing Machine Operators");
		occupationList.put("51-6040", "Shoe and Leather Workers");
		occupationList.put("51-6041", "Shoe and Leather Workers and Repairers");
		occupationList.put("51-6042", "Shoe Machine Operators and Tenders");
		occupationList.put("51-6050", "Tailors, Dressmakers, and Sewers");
		occupationList.put("51-6051", "Sewers, Hand");
		occupationList.put("51-6052", "Tailors, Dressmakers, and Custom Sewers");
		occupationList.put("51-6060", "Textile Machine Setters, Operators, and Tenders");
		occupationList.put("51-6061", "Textile Bleaching and Dyeing Machine Operators and Tenders");
		occupationList.put("51-6062", "Textile Cutting Machine Setters, Operators, and Tenders");
		occupationList.put("51-6063", "Textile Knitting and Weaving Machine Setters, Operators, and Tenders");
		occupationList.put("51-6064", "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders");
		occupationList.put("51-6090", "Miscellaneous Textile, Apparel, and Furnishings Workers");
		occupationList.put("51-6091", "Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers");
		occupationList.put("51-6092", "Fabric and Apparel Patternmakers");
		occupationList.put("51-6093", "Upholsterers");
		occupationList.put("51-6099", "Textile, Apparel, and Furnishings Workers, All Other");
		occupationList.put("51-7000", "Woodworkers");
		occupationList.put("51-7010", "Cabinetmakers and Bench Carpenters");
		occupationList.put("51-7020", "Furniture Finishers");
		occupationList.put("51-7030", "Model Makers and Patternmakers, Wood");
		occupationList.put("51-7031", "Model Makers, Wood");
		occupationList.put("51-7032", "Patternmakers, Wood");
		occupationList.put("51-7040", "Woodworking Machine Setters, Operators, and Tenders");
		occupationList.put("51-7041", "Sawing Machine Setters, Operators, and Tenders, Wood");
		occupationList.put("51-7042", "Woodworking Machine Setters, Operators, and Tenders, Except Sawing");
		occupationList.put("51-7090", "Miscellaneous Woodworkers");
		occupationList.put("51-8000", "Plant and System Operators");
		occupationList.put("51-8010", "Power Plant Operators, Distributors, and Dispatchers");
		occupationList.put("51-8011", "Nuclear Power Reactor Operators");
		occupationList.put("51-8012", "Power Distributors and Dispatchers");
		occupationList.put("51-8013", "Power Plant Operators");
		occupationList.put("51-8020", "Stationary Engineers and Boiler Operators");
		occupationList.put("51-8030", "Water and Wastewater Treatment Plant and System Operators");
		occupationList.put("51-8090", "Miscellaneous Plant and System Operators");
		occupationList.put("51-8091", "Chemical Plant and System Operators");
		occupationList.put("51-8092", "Gas Plant Operators");
		occupationList.put("51-8093", "Petroleum Pump System Operators, Refinery Operators, and Gaugers");
		occupationList.put("51-8099", "Plant and System Operators, All Other");
		occupationList.put("51-9000", "Other Production Occupations");
		occupationList.put("51-9010", "Chemical Processing Machine Setters, Operators, and Tenders");
		occupationList.put("51-9011", "Chemical Equipment Operators and Tenders");
		occupationList.put("51-9012", "Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders");
		occupationList.put("51-9020", "Crushing, Grinding, Polishing, Mixing, and Blending Workers");
		occupationList.put("51-9021", "Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders");
		occupationList.put("51-9022", "Grinding and Polishing Workers, Hand");
		occupationList.put("51-9023", "Mixing and Blending Machine Setters, Operators, and Tenders");
		occupationList.put("51-9030", "Cutting Workers");
		occupationList.put("51-9031", "Cutters and Trimmers, Hand");
		occupationList.put("51-9032", "Cutting and Slicing Machine Setters, Operators, and Tenders");
		occupationList.put("51-9040", "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders");
		occupationList.put("51-9050", "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders");
		occupationList.put("51-9060", "Inspectors, Testers, Sorters, Samplers, and Weighers");
		occupationList.put("51-9070", "Jewelers and Precious Stone and Metal Workers");
		occupationList.put("51-9080", "Medical, Dental, and Ophthalmic Laboratory Technicians");
		occupationList.put("51-9081", "Dental Laboratory Technicians");
		occupationList.put("51-9082", "Medical Appliance Technicians");
		occupationList.put("51-9083", "Ophthalmic Laboratory Technicians");
		occupationList.put("51-9110", "Packaging and Filling Machine Operators and Tenders");
		occupationList.put("51-9120", "Painting Workers");
		occupationList.put("51-9121", "Coating, Painting, and Spraying Machine Setters, Operators, and Tenders");
		occupationList.put("51-9122", "Painters, Transportation Equipment");
		occupationList.put("51-9123", "Painting, Coating, and Decorating Workers");
		occupationList.put("51-9140", "Semiconductor Processors");
		occupationList.put("51-9150", "Photographic Process Workers and Processing Machine Operators");
		occupationList.put("51-9190", "Miscellaneous Production Workers");
		occupationList.put("51-9191", "Adhesive Bonding Machine Operators and Tenders");
		occupationList.put("51-9192", "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders");
		occupationList.put("51-9193", "Cooling and Freezing Equipment Operators and Tenders");
		occupationList.put("51-9194", "Etchers and Engravers");
		occupationList.put("51-9195", "Molders, Shapers, and Casters, Except Metal and Plastic");
		occupationList.put("51-9196", "Paper Goods Machine Setters, Operators, and Tenders");
		occupationList.put("51-9197", "Tire Builders");
		occupationList.put("51-9198", "Helpers--Production Workers");
		occupationList.put("51-9199", "Production Workers, All Other");
		occupationList.put("53-0000", "Transportation and Material Moving Occupations");
		occupationList.put("53-1000", "Supervisors of Transportation and Material Moving Workers");
		occupationList.put("53-1010", "Aircraft Cargo Handling Supervisors");
		occupationList.put("53-1020", "First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand");
		occupationList.put("53-1030", "First-Line Supervisors of Transportation and Material-Moving Machine and Vehicle Operators");
		occupationList.put("53-2000", "Air Transportation Workers");
		occupationList.put("53-2010", "Aircraft Pilots and Flight Engineers");
		occupationList.put("53-2011", "Airline Pilots, Copilots, and Flight Engineers");
		occupationList.put("53-2012", "Commercial Pilots");
		occupationList.put("53-2020", "Air Traffic Controllers and Airfield Operations Specialists");
		occupationList.put("53-2030", "Flight Attendants");
		occupationList.put("53-3000", "Motor Vehicle Operators");
		occupationList.put("53-3010", "Ambulance Drivers and Attendants, Except Emergency Medical Technicians");
		occupationList.put("53-3020", "Bus Drivers");
		occupationList.put("53-3021", "Bus Drivers, Transit and Intercity ");
		occupationList.put("53-3022", "Bus Drivers, School or Special Client ");
		occupationList.put("53-3030", "Driver/Sales Workers and Truck Drivers");
		occupationList.put("53-3031", "Driver/Sales Workers");
		occupationList.put("53-3032", "Heavy and Tractor-Trailer Truck Drivers");
		occupationList.put("53-3033", "Light Truck or Delivery Services Drivers");
		occupationList.put("53-3040", "Taxi Drivers and Chauffeurs");
		occupationList.put("53-3090", "Miscellaneous Motor Vehicle Operators");
		occupationList.put("53-4000", "Rail Transportation Workers");
		occupationList.put("53-4010", "Locomotive Engineers and Operators");
		occupationList.put("53-4011", "Locomotive Engineers");
		occupationList.put("53-4012", "Locomotive Firers");
		occupationList.put("53-4013", "Rail Yard Engineers, Dinkey Operators, and Hostlers");
		occupationList.put("53-4020", "Railroad Brake, Signal, and Switch Operators");
		occupationList.put("53-4030", "Railroad Conductors and Yardmasters");
		occupationList.put("53-4040", "Subway and Streetcar Operators");
		occupationList.put("53-4090", "Miscellaneous Rail Transportation Workers");
		occupationList.put("53-5000", "Water Transportation Workers");
		occupationList.put("53-5010", "Sailors and Marine Oilers");
		occupationList.put("53-5020", "Ship and Boat Captains and Operators");
		occupationList.put("53-5021", "Captains, Mates, and Pilots of Water Vessels");
		occupationList.put("53-5022", "Motorboat Operators");
		occupationList.put("53-2011", "Airline Pilots, Copilots, and Flight Engineers");
		occupationList.put("53-2012", "Commercial Pilots");
		occupationList.put("53-5030", "Ship Engineers");
		occupationList.put("53-6000", "Other Transportation Workers");
		occupationList.put("53-6010", "Bridge and Lock Tenders");
		occupationList.put("53-6020", "Parking Lot Attendants");
		occupationList.put("53-6030", "Automotive and Watercraft Service Attendants");
		occupationList.put("53-6040", "Traffic Technicians");
		occupationList.put("53-6050", "Transportation Inspectors");
		occupationList.put("53-6060", "Transportation Attendants, Except Flight Attendants");
		occupationList.put("53-6090", "Miscellaneous Transportation Workers");
		occupationList.put("53-7000", "Material Moving Workers");
		occupationList.put("53-7010", "Conveyor Operators and Tenders");
		occupationList.put("53-7020", "Crane and Tower Operators");
		occupationList.put("53-7030", "Dredge, Excavating, and Loading Machine Operators");
		occupationList.put("53-7031", "Dredge Operators");
		occupationList.put("53-7032", "Excavating and Loading Machine and Dragline Operators");
		occupationList.put("53-7033", "Loading Machine Operators, Underground Mining");
		occupationList.put("53-7040", "Hoist and Winch Operators");
		occupationList.put("53-7050", "Industrial Truck and Tractor Operators");
		occupationList.put("53-7060", "Laborers and Material Movers, Hand");
		occupationList.put("53-7061", "Cleaners of Vehicles and Equipment");
		occupationList.put("53-7062", "Laborers and Freight, Stock, and Material Movers, Hand");
		occupationList.put("53-7063", "Machine Feeders and Offbearers");
		occupationList.put("53-7064", "Packers and Packagers, Hand");
		occupationList.put("53-7070", "Pumping Station Operators");
		occupationList.put("53-7071", "Gas Compressor and Gas Pumping Station Operators");
		occupationList.put("53-7072", "Pump Operators, Except Wellhead Pumpers");
		occupationList.put("53-7073", "Wellhead Pumpers");
		occupationList.put("53-7080", "Refuse and Recyclable Material Collectors");
		occupationList.put("53-7110", "Mine Shuttle Car Operators");
		occupationList.put("53-7120", "Tank Car, Truck, and Ship Loaders");
		occupationList.put("53-7190", "Miscellaneous Material Moving Workers");
		occupationList.put("55-0000", "Military Specific Occupations");
		occupationList.put("55-1000", "Military Officer Special and Tactical Operations Leaders");
		occupationList.put("55-1011", "Air Crew Officers");
		occupationList.put("55-1012", "Aircraft Launch and Recovery Officers");
		occupationList.put("55-1013", "Armored Assault Vehicle Officers");
		occupationList.put("55-1014", "Artillery and Missile Officers");
		occupationList.put("55-1015", "Command and Control Center Officers");
		occupationList.put("55-1016", "Infantry Officers");
		occupationList.put("55-1017", "Special Forces Officers");
		occupationList.put("55-1019", "Military Officer Special and Tactical Operations Leaders, All Other");
		occupationList.put("55-1010", "Military Officer Special and Tactical Operations Leaders");
		occupationList.put("55-2000", "First-Line Enlisted Military Supervisors");
		occupationList.put("55-2010", "First-Line Enlisted Military Supervisors");
		occupationList.put("55-2011", "First-Line Supervisors of Air Crew Members");
		occupationList.put("55-2012", "First-Line Supervisors of Weapons Specialists/Crew Members");
		occupationList.put("55-2013", "First-Line Supervisors of All Other Tactical Operations Specialists");
		occupationList.put("55-3000", "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members");
		occupationList.put("55-3010", "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members");
		occupationList.put("55-3011", "Air Crew Members");
		occupationList.put("55-3012", "Aircraft Launch and Recovery Specialists");
		occupationList.put("55-3013", "Armored Assault Vehicle Crew Members");
		occupationList.put("55-3014", "Artillery and Missile Crew Members");
		occupationList.put("55-3015", "Command and Control Center Specialists");
		occupationList.put("55-3016", "Infantry");
		occupationList.put("55-3017", "Radar and Sonar Technicians");
		occupationList.put("55-3018", "Special Forces");
		occupationList.put("55-3019", "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other");

	}
}
