<?php

namespace Societies\TestEngineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerformanceTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceTestRepository extends EntityRepository
{
}
