package org.societies.platform.socialdata;

import java.util.List;

import org.apache.shindig.social.opensocial.model.ActivityEntry;
import org.apache.shindig.social.opensocial.model.Group;
import org.apache.shindig.social.opensocial.model.Person;
import org.societies.platform.FacebookConn.SocialConnector;

public interface SocialData {

   
    /**
     * Add a new social connector to fetch data from a specific Social network
     * @param socialConnector Interface of the specific connector
     * @throws Exception 
     */
    void addSocialConnector(SocialConnector socialConnector) throws Exception;
    
    /**
     * Remove a social connector by his unique ID
     * @param connectorId
     * @throws Exception 
     */
    void removeSocialConnector(String connectorId) throws Exception;
    
    /**
     * Provide a list of the available social connector
     * @return List of Social Connector
     */
    List<SocialConnector> getSocialConnectors();
    
    /**
     * Provide the list of Profiles coming from different social Networks
     * @return
     */
    List<Person> getSocialProfiles();
    
    /**
     * Provide a list of Person Object extracted from all the connectors
     * @return List of Person
     */
    List<Person> getSocialPeople();
    
    
    /**
     * Provide the list of activity generated by the users in the social network.
     * @return List of ActivityEntry
     */
    List<ActivityEntry> getSocialActivity();
    
    /**
     * Provide a list of Groups generated in the social network
     * @return List of Group
     */
    List<Group> getSocialGroups();

    /**
     * Requeire the component to fetch from all active connector fetching data from the social networks
     */
    void updateSocialData();
    
    /**
     * Get last upated session
     */
    long getLastUpdate();
    
    
    /**
     * Check if the specific connector is available
     * @param connector Connetor instance
     * @return boolean
     */
    boolean isAvailable(SocialConnector connector);
}