<?php

namespace Societies\TestEngineBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TestResultController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Societies\TestEngineBundle\Controller\TestResultController();
        return $instance;
    }
}
