<?php

namespace Proxies\__CG__\Societies\TestEngineBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PerformanceTestResult extends \Societies\TestEngineBundle\Entity\PerformanceTestResult implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTestStartDate($testStartDate)
    {
        $this->__load();
        return parent::setTestStartDate($testStartDate);
    }

    public function getTestStartDate()
    {
        $this->__load();
        return parent::getTestStartDate();
    }

    public function setTestEndDate($testEndDate)
    {
        $this->__load();
        return parent::setTestEndDate($testEndDate);
    }

    public function getTestEndDate()
    {
        $this->__load();
        return parent::getTestEndDate();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setMessage($message)
    {
        $this->__load();
        return parent::setMessage($message);
    }

    public function getMessage()
    {
        $this->__load();
        return parent::getMessage();
    }

    public function setNode(\Societies\TestEngineBundle\Entity\Nodes $node = NULL)
    {
        $this->__load();
        return parent::setNode($node);
    }

    public function getNode()
    {
        $this->__load();
        return parent::getNode();
    }

    public function setPerformanceTest(\Societies\TestEngineBundle\Entity\PerformanceTest $performanceTest = NULL)
    {
        $this->__load();
        return parent::setPerformanceTest($performanceTest);
    }

    public function getPerformanceTest()
    {
        $this->__load();
        return parent::getPerformanceTest();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'testStartDate', 'testEndDate', 'status', 'message', 'node', 'performanceTest');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}