<?php

namespace Proxies\__CG__\Societies\TestEngineBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PerformanceTest extends \Societies\TestEngineBundle\Entity\PerformanceTest implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTestName($testName)
    {
        $this->__load();
        return parent::setTestName($testName);
    }

    public function getTestName()
    {
        $this->__load();
        return parent::getTestName();
    }

    public function setTestDescription($testDescription)
    {
        $this->__load();
        return parent::setTestDescription($testDescription);
    }

    public function getTestDescription()
    {
        $this->__load();
        return parent::getTestDescription();
    }

    public function setTestDeveloperName($testDeveloperName)
    {
        $this->__load();
        return parent::setTestDeveloperName($testDeveloperName);
    }

    public function getTestDeveloperName()
    {
        $this->__load();
        return parent::getTestDeveloperName();
    }

    public function addPerformanceTestParameter(\Societies\TestEngineBundle\Entity\PerformanceTestParameters $performanceTestParameters)
    {
        $this->__load();
        return parent::addPerformanceTestParameter($performanceTestParameters);
    }

    public function removePerformanceTestParameter(\Societies\TestEngineBundle\Entity\PerformanceTestParameters $performanceTestParameters)
    {
        $this->__load();
        return parent::removePerformanceTestParameter($performanceTestParameters);
    }

    public function getPerformanceTestParameters()
    {
        $this->__load();
        return parent::getPerformanceTestParameters();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'test_name', 'test_description', 'test_developer_name', 'performanceTestParameters');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}