<?php

namespace Proxies\__CG__\Societies\TestEngineBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class JoinCisTestResult extends \Societies\TestEngineBundle\Entity\JoinCisTestResult implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNodeId($nodeId)
    {
        $this->__load();
        return parent::setNodeId($nodeId);
    }

    public function getNodeId()
    {
        $this->__load();
        return parent::getNodeId();
    }

    public function setCisId($cisId)
    {
        $this->__load();
        return parent::setCisId($cisId);
    }

    public function getCisId()
    {
        $this->__load();
        return parent::getCisId();
    }

    public function setCssOwnerId($cssOwnerId)
    {
        $this->__load();
        return parent::setCssOwnerId($cssOwnerId);
    }

    public function getCssOwnerId()
    {
        $this->__load();
        return parent::getCssOwnerId();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setTestStartDate($testStartDate)
    {
        $this->__load();
        return parent::setTestStartDate($testStartDate);
    }

    public function getTestStartDate()
    {
        $this->__load();
        return parent::getTestStartDate();
    }

    public function setTestEndDate($testEndDate)
    {
        $this->__load();
        return parent::setTestEndDate($testEndDate);
    }

    public function getTestEndDate()
    {
        $this->__load();
        return parent::getTestEndDate();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nodeId', 'cisId', 'cssOwnerId', 'state', 'comment', 'testStartDate', 'testEndDate');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}