<?php

namespace Proxies\__CG__\Societies\TestEngineBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PerformanceTestParameters extends \Societies\TestEngineBundle\Entity\PerformanceTestParameters implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setParameterName($parameterName)
    {
        $this->__load();
        return parent::setParameterName($parameterName);
    }

    public function getParameterName()
    {
        $this->__load();
        return parent::getParameterName();
    }

    public function setParameterType($parameterType)
    {
        $this->__load();
        return parent::setParameterType($parameterType);
    }

    public function getParameterType()
    {
        $this->__load();
        return parent::getParameterType();
    }

    public function setParameterDescription($parameterDescription)
    {
        $this->__load();
        return parent::setParameterDescription($parameterDescription);
    }

    public function getParameterDescription()
    {
        $this->__load();
        return parent::getParameterDescription();
    }

    public function setParameterUnit($parameterUnit)
    {
        $this->__load();
        return parent::setParameterUnit($parameterUnit);
    }

    public function getParameterUnit()
    {
        $this->__load();
        return parent::getParameterUnit();
    }

    public function setPerformanceTest(\Societies\TestEngineBundle\Entity\PerformanceTest $performanceTest = NULL)
    {
        $this->__load();
        return parent::setPerformanceTest($performanceTest);
    }

    public function getPerformanceTest()
    {
        $this->__load();
        return parent::getPerformanceTest();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'parameter_name', 'parameter_type', 'parameter_description', 'parameter_unit', 'performanceTest');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}