package org.societies.api.internal.devicemgmt.device;



/**
 * <font color="#3f5fbf">Handler for the events generated by the device</font>
 * @author rafik
 * @version 1.0
 * @created 06-déc.-2011 15:38:57
 */
public interface DeviceListener {

	/**
	 * <font color="#3f5fbf">Device battery level has been updated.</font>
	 * <font color="#3f5fbf">It makes sense for devices implementing the Power Cluster.
	 * </font>
	 */
	public static final int EVENT_BATTERY_UPDATED = 4;
	/**
	 * <font color="#3f5fbf">Device has been disabled, so application must take care
	 * of it.</font>
	 */
	public static final int EVENT_DISABLED = 0;
	/**
	 * <font color="#3f5fbf">Device has been enabled and it is available</font>
	 */
	public static final int EVENT_ENABLED = 1;
	/**
	 * <font color="#3f5fbf">Device location has been updated.</font>
	 * <font color="#3f5fbf">It makes sense for devices implementing the Location
	 * Cluster.</font>
	 */
	public static final int EVENT_LOCATION_UPDATED = 3;
	/**
	 * <font color="#3f5fbf">Device is close be out of battery.</font>
	 * <font color="#3f5fbf">It makes sense for devices implementing the Power Cluster.
	 * </font>
	 */
	public static final int EVENT_LOW_BATTERY = 2;

	/**
	 * <font color="#3f5fbf">This method allows devices to notify other elements about
	 * events triggered by the device.</font>
	 * <font color="#7f9fbf"><b>@param</b></font><font color="#3f5fbf"> device Device
	 * that raised the event</font>
	 * <font color="#7f9fbf"><b>@param</b></font><font color="#3f5fbf"> event Event
	 * raised, one of the constanst defined in that interface</font>
	 * 
	 * @param device
	 * @param event
	 */
	public void deviceEvent(Device  device, int event);

}