/**
 * Copyright (c) 2011, SOCIETIES Consortium (WATERFORD INSTITUTE OF TECHNOLOGY (TSSG), HERIOT-WATT UNIVERSITY (HWU), SOLUTA.NET 
 * (SN), GERMAN AEROSPACE CENTRE (Deutsches Zentrum fuer Luft- und Raumfahrt e.V.) (DLR), Zavod za varnostne tehnologije
 * informacijske družbe in elektronsko poslovanje (SETCCE), INSTITUTE OF COMMUNICATION AND COMPUTER SYSTEMS (ICCS), LAKE
 * COMMUNICATIONS (LAKE), INTEL PERFORMANCE LEARNING SOLUTIONS LTD (INTEL), PORTUGAL TELECOM INOVAÇÃO, SA (PTIN), IBM Corp., 
 * INSTITUT TELECOM (ITSUD), AMITEC DIACHYTI EFYIA PLIROFORIKI KAI EPIKINONIES ETERIA PERIORISMENIS EFTHINIS (AMITEC), TELECOM 
 * ITALIA S.p.a.(TI),  TRIALOG (TRIALOG), Stiftelsen SINTEF (SINTEF), NEC EUROPE LTD (NEC))
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
 * conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.societies.api.internal.devicemgmt.device.sensor;

import org.societies.api.internal.devicemgmt.device.DeviceListener;



/**
 * <font color="#3f5fbf">Handler for the events generated by the sensor.</font>
 * @author rafik
 * @version 1.0
 * @created 06-d�c.-2011 15:39:01
 */
public interface SensorListener extends DeviceListener {

	/**
	 * <font color="#3f5fbf">The sensor has detected some event, like a gas leakage or
	 * any activity</font>
	 * <font color="#3f5fbf">(for sensors implementing the EventSensorCluster).</font>
	 */
	public static final int EVENT_EVENT_RAISED = 6;
	/**
	 * <font color="#3f5fbf">The lower threshold has been reached (for sensors
	 * implementing</font>
	 * <font color="#3f5fbf">ThresholdSensorCluster).</font>
	 */
	public static final int EVENT_LOWER_THRESHOLD_REACHED = 1;
	/**
	 * <font color="#3f5fbf">The sensor has rearmed itself after an event detection
	 * (for sensors</font>
	 * <font color="#3f5fbf">implementing the EventSensorCluster).</font>
	 */
	public static final int EVENT_SENSOR_ARMED = 7;
	/**
	 * <font color="#3f5fbf">The sensor has initiated a streaming procedure (for
	 * sensors implementing</font>
	 * <font color="#3f5fbf">StreamingSensorCluster).</font>
	 */
	public static final int EVENT_STREAMING_STARTED = 3;
	/**
	 * <font color="#3f5fbf">The sensor has stopped a streaming procedure(for sensors
	 * implementing</font>
	 * <font color="#3f5fbf">StreamingSensorCluster).</font>
	 */
	public static final int EVENT_STREAMING_STOPPED = 4;
	/**
	 * <font color="#3f5fbf">The upper threshold has been reached (for sensors
	 * implementing</font>
	 * <font color="#3f5fbf">ThresholdSensorCluster).</font>
	 */
	public static final int EVENT_UPPER_THRESHOLD_REACHED = 2;
	/**
	 * <font color="#3f5fbf">The sensor value has chaged with respect to the previous
	 * stored value.</font>
	 */
	public static final int EVENT_VALUE_CHANGED = 5;
	/**
	 * <font color="#3f5fbf">Value of the sensor has been updated and can be read with
	 * getValue()</font>
	 */
	public static final int EVENT_VALUE_UPDATED = 0;

	/**
	 * <font color="#3f5fbf">This method allows sensor to notify other elements about
	 * events  triggered by the sensor.</font>
	 * <font color="#7f9fbf"><b>@param</b></font><font color="#3f5fbf"> device Device
	 * that raised the event</font>
	 * <font color="#7f9fbf"><b>@param</b></font><font color="#3f5fbf"> event event
	 * raised, coded as one of the constants defined in these</font>
	 * <font color="#3f5fbf">interface</font>
	 * 
	 * @param device
	 * @param event
	 */
	public void deviceSensorEvent(Sensor device, int event);

}